ignorePatterns: ["dist", "node_modules"],
env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
rules: {
  quotes: ["error", "single"],
  semi: ["error", "never"],
  react/prop-types: "off",
  no-unused-vars: 1,
  no-case-declarations: 0,
  react/react-in-jsx-scope: 0,
  react-hooks/rules-of-hooks: "error",
  react-hooks/exhaustive-deps: "warn",
  prettier/prettier: "warn",
}